<a href="https://colab.research.google.com/github/ArindamRoy23/Huggin_Faces_Course/blob/main/HF_Using_Transformers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install datasets evaluate transformers[sentencepiece]


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 492.2/492.2 kB 5.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.4/81.4 kB 3.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.4/7.4 MB 19.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 115.3/115.3 kB 5.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 212.5/212.5 kB 12.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 4.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 268.8/268.8 kB 11.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 33.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 23.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 28.1 MB/s eta 0:00:00


In [2]:
from transformers import BertConfig, BertModel

# Defining Model

In [6]:
config = BertConfig()
# model = BertModel(config) #Random Weights without training
model = BertModel.from_pretrained("bert-base-cased")

# Tokenizing and converting to IDs

In [91]:
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification
checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)
model = AutoModelForSequenceClassification.from_pretrained(checkpoint)


sequence = "I've been waiting for a HuggingFace course my whole life."
tokens = tokenizer.tokenize(sequence)
ids = tokenizer.convert_tokens_to_ids(tokens)
input_ids = torch.tensor([ids])

In [92]:
output = model(input_ids)
print(output.logits)
batched_ids = [ids, ids]
input_batched_ids = torch.tensor(batched_ids)
output = model(input_batched_ids)
print(output.logits)


tensor([[-2.7276,  2.8789]], grad_fn=<AddmmBackward0>)
tensor([[-2.7276,  2.8789],
        [-2.7276,  2.8789]], grad_fn=<AddmmBackward0>)


# Using masks for long sentences

In [93]:
s1 = 'I’ve been waiting for a HuggingFace course my whole life.'
s2 = 'I hate this so much!'
t1 = tokenizer.tokenize(s1)
t2 = tokenizer.tokenize(s2)
i1 = tokenizer.convert_tokens_to_ids(t1)
i2 = tokenizer.convert_tokens_to_ids(t2)
pad_token_id = tokenizer.pad_token_id

add = len(i1) - len(i2)
while add!= 0:
  i2.append(pad_token_id)
  add-=1
input_ids = torch.tensor([i1,i2])
i1_mask = [1 if i!= pad_token_id else 0 for i in i1]
i2_mask = [1 if i!= pad_token_id else 0 for i in i2]
mask_ids = torch.tensor([i1_mask,i2_mask])
outputs = model(input_ids, mask_ids)
print(outputs.logits)

tensor([[-2.5720,  2.6852],
        [ 3.1931, -2.6685]], grad_fn=<AddmmBackward0>)
